### ISSUE TITLE
Subscription: date constraint doesn't work 

### ISSUE THREAD

**Issue by AstroJacobLi** [tangbao/NJ-MVC-Appointment-Helper#1]
Hi! I'd like to express my gratitude to you and this wonderful tool!

I ran the latest code on my own machine and used the `/subscribe` function. However, even after setting the "late date" (such as 211001), the bot keeps notifying me available slots after that date. Could you please help me take a look at this issue? Many thanks!

Cheers,
Jiaxuan

**Comment by tangbao** [comment]
I have noticed this problem yesterday. I am planning to fix it today. Thank you very much!

**Comment by tangbao** [comment]
Hi Jiaxuan,

I think I have fixed the bug. Please give it a try and let me know if you have any questions.

BTW, the bot will send runtime error messages to the admin now (you have to send ```/start``` to the bot using the admin Telegram account first). Hope it can help when you do some tests.

Best,
tangbao
